<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqHMo8O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqHMo8O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXqHMo8O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXqHMo8O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXqHMo8O\App_KernelDevDebugContainer([
    'container.build_hash' => 'XqHMo8O',
    'container.build_id' => '03796031',
    'container.build_time' => 1638473097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqHMo8O');
