<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVhQE115\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVhQE115/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVhQE115.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVhQE115\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVhQE115\App_KernelDevDebugContainer([
    'container.build_hash' => 'VhQE115',
    'container.build_id' => 'af75a564',
    'container.build_time' => 1638473326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVhQE115');
